FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Objective.Akinator.WebApi/Objective.Akinator.WebApi.csproj", "Objective.Akinator.WebApi/"]
RUN dotnet restore "Objective.Akinator.WebApi/Objective.Akinator.WebApi.csproj"
COPY . .
WORKDIR "/src/Objective.Akinator.WebApi"
RUN dotnet build "Objective.Akinator.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Objective.Akinator.WebApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Objective.Akinator.WebApi.dll"]